/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-105208-gb24f0c82b3-ffmpeg-windows-build-helpers"
#endif /* AVUTIL_FFVERSION_H */
